creation d'editRoom et modification tu tableau dans price par rapport…
WildCodeSchool/orleans-php-2003-project-fjt pull request #101
Opened 2020-05-05 22:24 UTC by JuGault

… a la bdd

2020-05-06 05:11 UTC, malyadev submitted a review, later dismissed
m'as l'air ok

2020-05-06 07:00 UTC, sblondeau requested changes

2020-05-06 07:00 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            $addressesId[] = $address['id'];
plutot que cette boucle, tu pourrais utiliser la fonction array_column (mais au final ça fait la meme chose^^)

2020-05-06 07:00 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +        $id = trim($_GET['id']);
l'id pour l'edit ne devrait pas passer par le GET, mais etre un paramètre de ta function, passée via une  route de format
adminRoom/edit/3
et ensuite editRoom(int $id) { ... }

2020-05-06 07:00 UTC, sblondeau commented on src/Controller/ItemController.php
> +    public function editRoom(int $id): string
comme c'est fait ici en fait ;-) 
mais là tu as modif (je pense par erreur) le fichier d'exemple sur les Item

2020-05-06 07:00 UTC, sblondeau commented on src/Model/AbstractManager.php
> +    public function selectOneById($id)
euh... non là il faut laisser le int, tes id sont tjs des int

2020-05-06 07:00 UTC, sblondeau commented on src/View/AdminRoom/index.html.twig
> +                                <a class="btn btn-outline-primary" href="../AdminRoom/editRoom/?id={{ room.id }}" value="">Mettre à jour</a>
ta route ne devrait pas commencer par "../"
ça devrait etre plutot "AdminRoom/editRoom/{{room.id}}"

2020-05-06 07:00 UTC, sblondeau commented on src/View/Price/index.html.twig
> +                <td>{% if room.area in [0] %}/{% else %}{{ room.area }} m²{% endif %}</td>
pas plutot if room.area == 0 ?

2020-05-06 08:39 UTC, JuGault commented on src/View/AdminRoom/index.html.twig
> +                                <a class="btn btn-outline-primary" href="../AdminRoom/editRoom/?id={{ room.id }}" value="">Mettre à jour</a>
ça concatene la route sinon si y'a pas "../"

2020-05-06 11:58 UTC, malyadev submitted a review, later dismissed
ok

2020-05-06 13:45 UTC, AnthonyMeyro submitted a review, later dismissed
:)

2020-05-07 08:52 UTC, sblondeau requested changes

2020-05-07 08:52 UTC, sblondeau commented on src/Controller/AdminAddressController.php
> +        $adminRoomManager = new RoomManager();
c'est bien d'avoir fait le AdminAddressController, qui a va gérer l'affichage des pages Admin pour l'adresse (le CRUD des adresse en gros)
par contre, tu appelle ici le RoomManager, et tu mets tes méthodes de requetes pour gérer les adresses dans ce RoomManager
Or, les adresses sont dans une autre table, donc tu dois avoir un AddressManager ! et dedans les requetes touchant aux adresses.

2020-05-07 08:52 UTC, sblondeau commented on src/Controller/AdminAddressController.php
> +                $adminRoomManager->insertAddress($data);
donc là ça deviendrait $addressManager->insert($data);

2020-05-07 14:19 UTC, malyadev submitted a review, later dismissed
relu

2020-05-09 07:03 UTC, sblondeau requested changes

2020-05-09 07:03 UTC, sblondeau commented on src/Controller/AdminAddressController.php
> +        $adminAddressManager = new AddressManager();
$adressManager

2020-05-09 07:03 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            $errors = array_merge($errorsDataOne, $errorsDataTwo, $errorsFilterOne, $errorsFilterTwo, $errorsUpload);
y aurais de l'optimisation possible sur ces 7-8 lignes qui sont exactement les memes coté edit et add non ?
ça pourrait etre intéressant d'avoir une seule méthode privée controlData() qui appelle toutes ce sous méthodes
comme ça tu n'aurais plus qu'à faire $errors->this->controlData()
resterait le soucis de $fileNameNew à recup
si tu reprends le livecoding, tu vois que je gère la génération de ce nom de fichier ET le move_upload_file dans une meme méthode, et je ne gènère pas le nom de fichier au meme moment que la validation du fichier; ça sépare mieux les choses.
Tout ce que je te mets là reste optionnel, ne perd pas de temps avec ça si tu ne le sens pas ;-)

2020-05-09 07:03 UTC, sblondeau commented on src/View/Price/index.html.twig
> +        <h2>Grille tarifaire:</h2>
en français, il faut une espace entre la lettre et les ":" ;-)
mais enlève le ":" il est inutile

2020-05-09 07:04 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            $errors = array_merge($errorsDataOne, $errorsDataTwo, $errorsFilterOne, $errorsFilterTwo, $errorsUpload);
au pire garde ça pour un fix plus tard

2020-05-09 10:25 UTC, JuGault commented on src/Controller/AdminRoomController.php
> +            $errors = array_merge($errorsDataOne, $errorsDataTwo, $errorsFilterOne, $errorsFilterTwo, $errorsUpload);
oui plus tard dans un fix la y'a pas mal de pett truc a passer j'ai pas le temps de m'en occupé de suite

2020-05-09 10:47 UTC, malyadev submitted a review, later dismissed
oui

2020-05-09 18:39 UTC, sblondeau requested changes

2020-05-09 18:39 UTC, sblondeau commented on src/View/Price/index.html.twig
> +<<<<<<< HEAD
te reste des trace de conflit mal réglé !!!!
le code reviewer me doit un gateau là !

2020-05-10 08:38 UTC, malyadev requested changes

2020-05-10 08:38 UTC, malyadev commented on src/Controller/AdminRoomController.php
> +            $errorsDataOne['address_id'] = 'L\'adresse du logement n\'est pas une adresse éxistante';
existante sans accent :) et j'aurai changé la formulation pour " l'adresse n'existe pas dans la base de données " plutôt, parce que dire à l'administrateur que son adresse n'existe pas.. bof mdr

2020-05-10 08:38 UTC, malyadev commented on src/Controller/AdminRoomController.php
> +            $errorsFilterOne['guarantee'] = 'La valeur du dépôt de garantie n\'est pas autorisé';
valeur, donc autoriséE

2020-05-10 11:06 UTC, AnthonyMeyro approved these changes
k

2020-05-11 07:50 UTC, sblondeau approved these changes

2020-05-11 07:50 UTC, merged