fix_dev : modification du lien pour l'ajout d'adresse
WildCodeSchool/orleans-php-2003-project-fjt pull request #109
Opened 2020-05-06 17:07 UTC by Heldeenn

2020-05-06 17:11 UTC, AnthonyMeyro submitted a review, later dismissed
Ok!

2020-05-07 06:49 UTC, sblondeau requested changes

2020-05-07 06:49 UTC, sblondeau commented on src/View/AdminRoom/index.html.twig
> +                <a role="button" class="btn btn-outline-primary btn-lg" href="../AdminRoom/addAddress">Ajouter une adresse</a>
les "../" devant la route ne sont pas nécessaires
essaie juste "/Admin/index" ou "/AdminRoom/addAddress"

2020-05-07 07:02 UTC, AnthonyMeyro approved these changes
approved

2020-05-07 08:53 UTC, sblondeau approved these changes

2020-05-07 08:53 UTC, merged