S04 us24 admin admission
WildCodeSchool/orleans-php-2003-project-fjt pull request #111
Opened 2020-05-06 20:17 UTC by JuGault

2020-05-07 06:52 UTC, AnthonyMeyro submitted a review, later dismissed
k

2020-05-09 10:12 UTC, sblondeau requested changes
faut que tu m'expliques clairement ce que tu essaie de faire avec le zip et le multiexplode, le code est pas vraiment compréhensible en l'état ;-)

2020-05-09 10:12 UTC, sblondeau commented on src/Controller/AdminAdmissionController.php
> +use App\Model\AdminAdmissionManager;
non, ton entité c'est Admission (ta table en BDD est admission)
donc AdmissionManager. 
Que tu appelles ton manager pour une page coté visiteur ou coté admin ça ne change pas, ca reste le AdmissionManager

Tu préfixes avec Admin... quand tu créé un controlleur qui va afficher des pages coté admin.

2020-05-09 10:12 UTC, sblondeau commented on src/Controller/AdminAdmissionController.php
> +class AdminAdmissionController extends AbstractController
donc là c''est le bon nom

2020-05-09 10:12 UTC, sblondeau commented on src/Controller/AdminAdmissionController.php
> +        $admissionManager = new AdminAdmissionManager();
par contre ici, en plus tu m'appelles correctement la variable mais pas la classe :p

2020-05-09 10:12 UTC, sblondeau commented on src/Controller/AdminAdmissionController.php
> +            $folders[$i]['fold'] = $exploded[8];
je ne comprends pas ce que tu cherches à faire
Mais ça ne me parait pas très propre
explode sur plein de caractères puis récup le 9ème élément ? mais pourquoi ? :D

2020-05-09 10:12 UTC, sblondeau commented on src/Model/AdminAdmissionManager.php
> +    public function selectAllFolder(string $search = ''): array
pourquoi à tu un search ?pour chercher par nom ? 
là clairement c'est une autre US... y a beaucoup trop de chose dans cette PR

2020-05-09 10:51 UTC, JuGault commented on src/Controller/AdminAdmissionController.php
> +            $folders[$i]['fold'] = $exploded[8];
c'est pour générer arbitrairement un numero de dossier en "lien" avec l'uniquid de l'image c'est pour le style

2020-05-09 12:32 UTC, malyadev submitted a review, later dismissed
RAS

2020-05-11 09:16 UTC, sblondeau requested changes
il faut simplifier le multipleexplode, on en discute

2020-05-11 10:14 UTC, malyadev approved these changes
m'as l'air ok

2020-05-11 13:22 UTC, sblondeau approved these changes

2020-05-11 13:22 UTC, merged