S04 us34 avoir accès formulaire contact
WildCodeSchool/orleans-php-2003-project-fjt pull request #117
Opened 2020-05-10 08:13 UTC by malyadev

2020-05-10 10:44 UTC, JuGault commented on src/View/Contact/_form.html.twig
> +                        <div class="formErrors">
à delete je pense vu qu'il n'y a aucune erreurs correspondante?

2020-05-10 10:44 UTC, JuGault commented on src/View/Contact/_form.html.twig
> +                        </div>
Ici à compléter je pense car il y'a une erreur correspondante?

2020-05-10 10:45 UTC, JuGault requested changes
quelque modifs sur l'affichage des erreurs

2020-05-10 12:37 UTC, JuGault submitted a review, later dismissed
ok

2020-05-10 13:02 UTC, JuGault approved these changes

2020-05-11 08:15 UTC, sblondeau approved these changes

2020-05-11 08:15 UTC, merged