S04 us09 visualiser prises de contact
WildCodeSchool/orleans-php-2003-project-fjt pull request #118
Opened 2020-05-10 08:22 UTC by malyadev

2020-05-10 10:49 UTC, JuGault commented on src/Controller/HomeController.php
> +
la partie en dessous est pour la partie administrateur ? du coup cela devrait se trouver dans une partie AdminContactController avec la partie show qui deviendrait index et la partie message qui deviendrait show ?

2020-05-10 10:52 UTC, JuGault commented on src/Controller/HomeController.php
> +        $contact = $contactManager->selectAllContact();
le nommage est peut être pas explicite ? contacts eventuellement il risque d'y en avoir plusieurs, et peut être messages ?

2020-05-10 10:52 UTC, JuGault commented on src/Controller/HomeController.php
> +        return $this->twig->render('Admincontact/message.html.twig', ['contacts' => $contact]);
et ici message vu que y'en a qu'un

2020-05-10 10:56 UTC, JuGault requested changes
quelque modif a faire , le nommage me perturbe un peu sur t'vu admin, index/show mais j'en suis pas sûr, et il faut au minimum créer un AdminContactController

2020-05-10 16:49 UTC, JuGault approved these changes
ok

2020-05-11 09:01 UTC, sblondeau requested changes

2020-05-11 09:01 UTC, sblondeau commented on src/View/Admincontact/index.html.twig
> +                <button class="btn btn-outline-secondary " type="button" value="button">Retour à l'accueil</button>
pas un button dans un a ! tu mets une class="btn" direct sur la balise a

2020-05-11 09:01 UTC, sblondeau commented on src/View/Admincontact/index.html.twig
> +                <td> <a href="/AdminContact/show/{{ contact.id }}"><button class="btn btn-outline-primary" type="button" value="button" >Consulter</button></a>
bas de button dans le a

2020-05-11 09:01 UTC, sblondeau commented on src/Controller/AdminContactController.php
> +        return $this->twig->render('Admincontact/show.html.twig', ['contacts' => $contact]);
'contact'=>$contact
tu n'as qu'un seul contact là

2020-05-11 09:04 UTC, sblondeau requested changes
ta branche est tirée depuis S04_US10_suppression_prises_de_contact
ça ne va pas, il faut que tes branches soient toutes tirées depuis dev !

2020-05-11 12:05 UTC, closed without merging