S04 US10 suppression prises de contact
WildCodeSchool/orleans-php-2003-project-fjt pull request #119
Opened 2020-05-10 08:26 UTC by malyadev

2020-05-10 10:58 UTC, JuGault commented on src/Controller/HomeController.php
> +
la partie delete a mettre dans un AdminContactController

2020-05-10 11:00 UTC, JuGault requested changes
Idem partie AdminContactController, que tu fait existait dans tes vu twig a priori donc il doit existait

2020-05-10 16:51 UTC, JuGault submitted a review, later dismissed
ok

2020-05-11 06:56 UTC, AnthonyMeyro approved these changes
k

2020-05-11 09:11 UTC, closed without merging