Graphical charter definition
WildCodeSchool/orleans-php-2003-project-fjt pull request #13
Opened 2020-04-14 14:42 UTC by AnthonyBerduck

Definition de la charte graphique avec mes meilleurs potes.

2020-04-14 14:44 UTC, Heldeenn submitted a review, later dismissed
Ok

2020-04-14 15:27 UTC, sblondeau requested changes
manque l'ajout de boostrap également

2020-04-14 15:27 UTC, sblondeau commented on public/assets/css/style.css
> +    -webkit-box-sizing: border-box;
les 2 box-sizing avec prefixes moz et webkit sont inutiles

2020-04-14 16:22 UTC, sblondeau requested changes

2020-04-14 16:22 UTC, sblondeau commented on src/View/layout.html.twig
> +    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></
nope, dsl
le JS se mets juste avant la fermeture du body (juste avant le {% block javascripts %} pour etre précis)
regardez l'exemple là par ex https://getbootstrap.com/docs/4.4/getting-started/introduction/#starter-template

2020-04-14 16:22 UTC, sblondeau commented on src/View/layout.html.twig
> +
donc les 3 ligne JS à mettre ici

2020-04-14 16:32 UTC, JuGault commented on src/View/layout.html.twig
> +
un choix d'équipe mais j'étais contre

2020-04-14 17:20 UTC, JuGault approved these changes

2020-04-15 06:03 UTC, malyadev reviewed
ok

2020-04-15 07:14 UTC, sblondeau approved these changes

2020-04-15 07:14 UTC, merged