methode delete et bouton supprimer ok
WildCodeSchool/orleans-php-2003-project-fjt pull request #139
Opened 2020-05-11 15:53 UTC by malyadev

2020-05-11 16:02 UTC, Heldeenn submitted a review, later dismissed

2020-05-11 16:06 UTC, sblondeau requested changes

2020-05-11 16:06 UTC, sblondeau commented on src/View/AdminContact/show.html.twig
> +                    <a href="/AdminContact/delete/{{contact.id}}" class="btn btn-outline-danger"> Supprimer </a>
non, en POST via un form le delete

2020-05-11 16:06 UTC, sblondeau commented on src/Controller/AdminContactController.php
> +        $contactManager = new ContactManager();
non l'id doit venir d'une recup en POST d'un form

2020-05-11 20:12 UTC, AnthonyMeyro approved these changes
K

2020-05-12 06:40 UTC, sblondeau approved these changes

2020-05-12 06:40 UTC, merged