S05_US28_download
WildCodeSchool/orleans-php-2003-project-fjt pull request #140
Opened 2020-05-11 17:02 UTC by JuGault

2020-05-11 20:07 UTC, malyadev submitted a review, later dismissed
ras

2020-05-12 06:47 UTC, sblondeau requested changes

2020-05-12 06:47 UTC, sblondeau commented on src/Model/AdmissionManager.php
> +    public function download()
pourquoi je retrouve à nouveau cette méthode dans le manager ?

2020-05-12 07:04 UTC, AnthonyMeyro submitted a review, later dismissed
k

2020-05-12 11:37 UTC, sblondeau submitted a review, later dismissed

2020-05-12 12:04 UTC, AnthonyMeyro approved these changes
K

2020-05-12 13:30 UTC, sblondeau requested changes

2020-05-12 13:30 UTC, sblondeau commented on src/View/AdminAdmission/show.html.twig
> +            </form>
hum
en fait un simple `<a href="{{ folder.zip_path }}">Télécharger</a>` doit très bien fonctionner
tu n'as pas besoin de passer par un form, ni de faire du coup une méthode download
test mais je pense que ça doit fonctionner comme ça

2020-05-12 13:40 UTC, closed without merging