fix_AdminAdmission
WildCodeSchool/orleans-php-2003-project-fjt pull request #192
Opened 2020-05-13 18:26 UTC by JuGault

…s bou correction route download/ amélioration  du design / modification des boutons

2020-05-13 19:03 UTC, AnthonyMeyro submitted a review, later dismissed
k

2020-05-13 21:43 UTC, sblondeau requested changes

2020-05-13 21:43 UTC, sblondeau commented on src/Model/AdmissionManager.php
> +        $statement = $this->pdo->prepare("UPDATE " . self::TABLE . " SET `statut` = :statut WHERE id=:id");
hum... on écrit bien statut en français, mais pour le coup en anglais c'est bien status... donc ton nom de champ et tes variable et ton name de formulaire devrais rester en "status"; tu n'a à mettre "statut" que pour la vue (label, message d'erreur, etc)

2020-05-13 21:43 UTC, sblondeau commented on src/View/AdminAdmission/index.html.twig
>              {% for folder in folders %}
si je ne dis pas de betise, en twig pour gagner un peu de temps, tu peux faire direct un 
`{% for folder in folders if folder.status is same as('En attente') %}`
(avec bien sur status et pas statut, voir remarque plus haut :p)

2020-05-14 07:12 UTC, malyadev approved these changes
oke

2020-05-14 07:50 UTC, sblondeau approved these changes

2020-05-14 07:50 UTC, merged