S01_US01 Navbar 1.0 Created
WildCodeSchool/orleans-php-2003-project-fjt pull request #31
Opened 2020-04-17 09:03 UTC by AnthonyBerduck

Navbar 1.0 created with the background img of the homepage to see the render of it.

2020-04-20 06:54 UTC, sblondeau requested changes
l'une des images fait plus de 1Mo, beaucoup trop gros. Reduire à environ 100Ko devrait etre suffisant

2020-04-21 15:07 UTC, malyadev approved these changes

2020-04-21 15:25 UTC, JuGault approved these changes

2020-04-21 18:39 UTC, sblondeau approved these changes

2020-04-21 18:39 UTC, merged