clean commit et PR US29
WildCodeSchool/orleans-php-2003-project-fjt pull request #43
Opened 2020-04-21 14:58 UTC by JuGault

2020-04-21 15:25 UTC, Heldeenn submitted a review, later dismissed

2020-04-21 18:50 UTC, sblondeau requested changes

2020-04-21 18:50 UTC, sblondeau commented on public/assets/css/price.css
> +        display: none!important;
deja, pas de !important
ensuite, je ne comprends pas bien à quoi sert cette media queries ?

2020-04-21 18:50 UTC, sblondeau commented on src/View/Price/index.html.twig
>              <div class=" col-1 "></div>
tu n'as pas à mettre de col-1 avant et après
dans ta div en dessous, tu dois utiliser offset-1 pour faire l'équivalent, je te laisse rejeter un oeil à la doc de boostrap là dessus ;-)

2020-04-21 18:50 UTC, sblondeau commented on src/View/Price/index.html.twig
>              <div class=" col-1"></div>
celle ci est inutile aussi

2020-04-21 18:50 UTC, sblondeau commented on src/View/Price/index.html.twig
> +            {% endfor %}
c'est pas optimisé
essaie plutot qq chose comme ça (teste le code je tape ça direct sur github je peux faire une erreur)
```   
{% set room_price =  ((room.guarantee+room.restoration+room.contribution+room.equipment_contribution)/30) %}
{% if room.breakfast is not null and room.breakfast != 'inclus' %}
         {% set room_price = room_price + room.breakfast %}
{% endif %}
 {{  room_price |round(2, 'floor') }}
```

2020-04-21 18:50 UTC, sblondeau commented on src/View/Price/index.html.twig
> +                <p>{% if room.breakfast is null or room.breakfast is same as('inclus') %}
meme opti ici

2020-04-21 18:50 UTC, sblondeau commented on src/View/Price/index.html.twig
> +                    {% if room.breakfast is null or room.breakfast is same as('inclus') %}
idem

2020-04-21 18:50 UTC, sblondeau commented on src/View/Price/index.html.twig
> +                    {% if room.breakfast is null or room.breakfast is same as('inclus') %}
je suis vraiment pas fan que tu fasses autant de boucles sur rooms que d'affichage, c'est vraiment pas optmisé et ça complexifie beaucoup ton code... je te ferai peut-etre changer ça plus tard :p

2020-04-21 20:04 UTC, JuGault commented on public/assets/css/price.css
> +        display: none!important;
le important c'pour écraser le display flex de bootstrap qui lui est en important et la média c'pour faire disparaitre le tableau en dessous de 768px

2020-04-22 07:31 UTC, AnthonyMeyro approved these changes

2020-04-22 07:56 UTC, AnthonyMeyro submitted a review, later dismissed

2020-04-22 13:17 UTC, AnthonyMeyro approved these changes

2020-04-22 15:37 UTC, sblondeau approved these changes

2020-04-22 15:37 UTC, merged