S02 us13 creation cards animations
WildCodeSchool/orleans-php-2003-project-fjt pull request #44
Opened 2020-04-22 07:27 UTC by Heldeenn

2020-04-22 07:35 UTC, AnthonyMeyro submitted a review, later dismissed

2020-04-22 07:45 UTC, sblondeau requested changes

2020-04-22 07:45 UTC, sblondeau commented on public/assets/css/service.css
> +}
beaucoup trop de media queries, je pense que tu peux t'en passer avec une meilleure exploitation de bootstrap ;-)

2020-04-22 07:45 UTC, sblondeau commented on src/View/Service/index.html.twig
>              <div class="col-md-6 col-xs-1 card-deck">
col-xs-1? ça me parait étrange...
Déjà il faut mettre seulement col-1 et pas col-xs-1 pour la plus petite taille
ensuite j'ai du mal à voir ta mise en page qui ferait 6 en md ou plus grand et seulement 1 en xs et s... tu voulais pas mettre 12 plutot ? (dans ce cas pas besoin de le préciser car c'est 12 par défaut)

2020-04-22 07:45 UTC, sblondeau commented on src/View/Service/index.html.twig
> +        {% if firstAnimation == true %}
tu as loop.first que tu peux utiliser dans une boucle pour savoir si tu es au 1er tour ou non, donc pas besoin de créer firstAnimation, c'est plus simple.

après, ton code quand c'est first ou pas first est relativement proche (tu affiches l'image, le name etc) donc là tu te répètes beaucoup (pas DRY). Je pense que c'est optimisable.
Y a des choses aussi qui peuvent etre gérer direct en CSS (avec :first-child par ex)

2020-04-23 07:53 UTC, malyadev submitted a review, later dismissed
convaincu

2020-04-23 16:39 UTC, malyadev approved these changes
oui

2020-04-23 19:15 UTC, sblondeau approved these changes

2020-04-23 19:15 UTC, merged