S02 US03 HomePage FJT
WildCodeSchool/orleans-php-2003-project-fjt pull request #46
Opened 2020-04-22 13:10 UTC by AnthonyBerduck

Homepage desktop done.

2020-04-22 13:18 UTC, Heldeenn submitted a review, later dismissed

2020-04-22 16:08 UTC, sblondeau requested changes

2020-04-22 16:08 UTC, sblondeau commented on public/assets/css/home.css
>          margin-left: -512px;   /* 50% */
c'est moche toutes ces valeurs, entre le 10**1** vw ? pourquoi pas 100 ?
et dans la medio query, le -512px plus un absolute en 100px, ça me parait un peu "bricolage" :p 
ton image, du devrais la mettre en background-image à mon sens, ça serait extremement plus simple non ?

2020-04-22 16:47 UTC, AnthonyBerduck commented on public/assets/css/home.css
>          margin-left: -512px;   /* 50% */
J'ai rajoute 1vh parce que j'observais que dans certains cas il restait une colonne de blanc a droite. Pour l'image, je me sens toujours plus libre au niveau du CSS pour pouvoir faire des modifications / animations quand je n'utilise pas le background image. De ce que j'ai vu il y a l'air d'avoir plusieurs ecoles a ce niveau la mais si tu veux je change ca pas de soucis, au moins eviter les margin en negatif :)

2020-04-23 08:42 UTC, Heldeenn submitted a review, later dismissed

2020-04-23 20:02 UTC, sblondeau requested changes

2020-04-23 20:02 UTC, sblondeau commented on public/assets/css/home.css
> +@media screen and (max-width: 1024px) {
pas la peine, utilise la classe bootstrap d-none avec la bonne taille d-sm-none, d-md-none, etc
https://getbootstrap.com/docs/4.4/utilities/display/#hiding-elements

2020-04-23 20:02 UTC, sblondeau commented on public/assets/css/home.css
> +::-webkit-input-placeholder {
non c'est déconseillé d'utiliser des prefixes qui vont etre propres aux navigateurs
utilise plutot   https://developer.mozilla.org/fr/docs/Web/CSS/::placeholder
et ça va etre plutot `input::placeholder` (le peudo-element CSS doit se placer après un sélecteur)

2020-04-23 20:02 UTC, sblondeau commented on public/assets/css/home.css
> +::-webkit-input-placeholder {
bon après, as tu vraiment besoin de styliser le placeholder? c'est un autre débat ;-)

2020-04-24 06:39 UTC, malyadev approved these changes
RAS

2020-04-24 06:51 UTC, sblondeau approved these changes

2020-04-24 06:52 UTC, merged