Fix_form
WildCodeSchool/orleans-php-2003-project-fjt pull request #48
Opened 2020-04-23 21:01 UTC by malyadev

2020-04-23 22:04 UTC, AnthonyMeyro approved these changes

2020-04-24 06:56 UTC, sblondeau requested changes

2020-04-24 06:56 UTC, sblondeau commented on src/Controller/ContactController.php
> +            $data = array_map('stripcslashes', $_POST);
non pas de stripslash c'est inutilie et htmlentities il ne faut le faire que à l'affichage, pas avant les validations, car ça peut modifier la taille de ta chaine de caractère et fausser ladite validation

2020-04-24 06:56 UTC, sblondeau commented on src/View/Service/index.html.twig
> +            <div class="col-md-6 col-xs-1 card-deck">
col-1 direct pour la petite taille et pas col-xs-1
https://getbootstrap.com/docs/4.4/layout/grid/#grid-options

2020-04-24 06:56 UTC, sblondeau commented on src/View/Service/index.html.twig
> +                        <figcaption></figcaption>
c'est normal un figcaption vide?  il manque pas une info ? ou alors il faut peut etre le mettre à la place du div avec la classe card-body ?

2020-04-24 07:00 UTC, Heldeenn commented on src/View/Service/index.html.twig
> +                        <figcaption></figcaption>
c'est ma partie tout ça (et le commentaire d'au dessus) et ça a déjà été modifié et merged !

2020-04-24 07:00 UTC, malyadev commented on src/Controller/ContactController.php
> +            $data = array_map('stripcslashes', $_POST);
il y a une erreur de ma part les validations n'étaient pas censées apparâitre sur cette PR elle est juste là pour fixer le formulaire

2020-04-24 07:06 UTC, closed without merging