S03 us31 création admin room
WildCodeSchool/orleans-php-2003-project-fjt pull request #62
Opened 2020-04-25 22:12 UTC by JuGault

2020-04-26 12:49 UTC, Heldeenn commented on src/View/AdminRoom/index.html.twig
> +                    <button class="btn btn-outline-primary btn-lg">Ajouter un logment</button>
Tu as oublié un 'e' à logement pour le bouton ;)

2020-04-26 12:56 UTC, JuGault commented on src/View/AdminRoom/index.html.twig
> +                    <button class="btn btn-outline-primary btn-lg">Ajouter un logment</button>
c'fait =p

2020-04-26 13:05 UTC, Heldeenn submitted a review, later dismissed

2020-04-26 20:17 UTC, sblondeau requested changes

2020-04-26 20:17 UTC, sblondeau commented on public/assets/css/adminRoom.css
> +    width: 33.33%;
non ce n'est pas une bonne pratique, car c'est un arrondi ! 
il faut plutot faire un calc(100%/3)

2020-04-26 20:17 UTC, sblondeau commented on src/View/AdminRoom/index.html.twig
> +                {% for room in rooms %}
c'est pas mal ce que tu as fais, mais y a un soucis d'optimisation, car tu fais 2 requetes SQL, puis tu boucles à chaque fois sur la totalité des rooms, pour chaque adresses.
Le mieux serait de faire une seule requete en BDD (avec une jointure), puis coté controller construire un tableau du style
$roomByAddresses[$adressName][] = $room;
que tu envoies à ta vue, et ensuite tu boucles dessus

2020-04-27 09:44 UTC, malyadev submitted a review, later dismissed
propre je trouve

2020-04-27 09:44 UTC, AnthonyMeyro submitted a review, later dismissed
Approved

2020-04-27 09:49 UTC, AnthonyMeyro approved these changes
OK

2020-04-27 12:16 UTC, sblondeau approved these changes

2020-04-27 12:16 UTC, merged