création de la partie AdminRoom add
WildCodeSchool/orleans-php-2003-project-fjt pull request #65
Opened 2020-04-27 15:15 UTC by JuGault

2020-04-27 15:27 UTC, malyadev commented on src/View/AdminRoom/_form.html.twig
> +        <label for="restoration">Crédit restauration : </label>
catering à la place de restoration :)

2020-04-27 15:41 UTC, malyadev submitted a review, later dismissed
ok

2020-04-27 16:16 UTC, malyadev submitted a review, later dismissed
better :)

2020-04-28 10:08 UTC, sblondeau requested changes

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +        chmod('../public/assets/images/', 0755);
inutile, si c'est toi qui créé le dossier tu as les droits dessus, n'utilise pas chmod() direct dans PHP

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +        $addresses = $adminRoomManager->selectAddress();
tu as déjà un RoomManager, pas la peine de créer un AdminRoomManager !
par contre OK pour le AdminRoomController car là c'est bien des pages différentes qui sont appelée, dans une partie spécifique du site, mais les "données" sont les memes, tu fais tes requetes sur la meme table, que tu sois coté admin que visiteur

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            if (!empty($_POST)) {
tu es déjà dans REQUEST_METHOD==="POST" donc ton $_POST ne doit pas etre vide, ce if est inutile

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +                $dataTmp = $this->controlData($data, $dataTmp);
pourquoi 2 paramètre à cette méthode ? le but est de passer $date et de récupérer un tableau $dataErrors, tu te compliques
vire ce $dataTmp

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +                $dataTmp = $this->controlDataFilter($data, $dataTmp);
cette méthode est inutile, elle devrait etre fusionnée avec controlData()

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +                $dataTmp = $this->controlDataFile($file, $dataTmp, $data);
ok pour mettre les controle du fichier dans une autre méthode, ça se justifie plus car tu ne traites pas la meme chose, mais dans ce cas $file est suffisant en paramètre, et tu récupère un tableau contenant le $fileName généré et $uploadErrors
donc $upload =  $this->controlDataFile($data);
$data['picture'] = $upload[0];
$uploadErrors = $upload[1];
(voir plus bas mes comments sur ta gestion de l'upload)

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +                list($errors, $data) = $dataTmp;
en fait tu fais plein de choses très compliquées pour juste réussir à fusionner tes tableaux d'erreurs...
un simple $errors = array_merge($dataErrors, $uploadErrors); fonctionne et t'évite le list(), t'évite le passage de param inutile.

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +                if (!empty($errors) && !empty($data['picture'])) {
tu es sur la methode add(), pourquoi fais tu un unlink ici ? ça doit etre géré dnas une future méthode pour delete une room, mais surement pas ici , à retirer

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +        return $dataTmp;
renomme $dataTmp en juste $errors, ça sera plus clair
et type les params d'entrée et la sortie de tes fonctions !

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +    private function controlDataFilter($data, $dataTmp)
retour à la ligne manquant entre les deux fonctions

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            $dataTmp['guarantee'] = 'La valeur du dépôt de garantie n\'est pas autorisé';
je mettrais plutot, "n'est pas une valeur numérique", c'est plus parlant pour l'utilisateur qui saura comment corrigé son erreur

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            $dataTmp['area'] = 'La valeur de la surface n\'est pas autorisée';
c'est pas un float ? si c'est bien le cas, préciser là encore dans le message d'erreur
"La valeur doit etre un nombre entier"

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            $dataTmp['address_id'] = 'La valeur de l\'adresse n\'est pas autorisée';
non ta vérif n'est pas suffisante. Vu que tu as une relation entre les deux tables, il ne faut pas vérifier que tu as un entier, mais plutot que tu cherche à entrer id qui se trouve dans un de ceux de la table adresse ! 
Il faut donc que tu récupères toutes les adresses via un AddressManager à créer si besoin. (puis un $addresses = $addressManager->selectAll()) et ensuite tu vérifie si $data['address_id'] est bien in_array les ids de $addresses ! (on verra ça en livecoding cet aprem normalement ;-))

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +        if (!empty($file['picture'])) {
envoie direct $file['picture'] en paramètre de ta méthode (et pas $file) ça t'évite d'avoir à faire cette vérif ici et économise un if

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            $uploadDir = '../public/assets/images/';
non, tes fichiers uploadés ne SONT PAS des assets. Les assets/images sont les images statiques du site, décoratives, non administrables. Là ce que tu upload ce sont des données, non versionnées, met les plutot dans un dossier "public/uplaods/" qui sera non versionné sur github.
D'ailleurs, tu peux créer une constante de classe plutot que de mettre cette valeur en dur, ça sera plus facile à modifier si besoin

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            $allowed = array('png', 'gif', 'jpg');
utilise la syntaxe [] plutot que array()

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            $allowed = array('png', 'gif', 'jpg');
et ce sont des type mime, et pas des extensions que tu dois mettre ici

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            if (!in_array($fileExt, $allowed, true)) {
c'est pas l'extension, mais le type mime que tu dois récup et comparer (voir quete upload)

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            if ($fileSize > 1000000) {
le max size peut etre mis en constante et non "en dur". Ainsi c'est facile à modifier, et tu peux reprendre la valeur dans le message d'erreur du styel "Le fichier dois faire moins de (self::MAX_FILE_SIZE/1000)Mo ", ce qui est plus facile pour l'user, sinon il doit tatonner jusqu'à avoir réduit suffisamment son image

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            if (!move_uploaded_file($fileTmp, $fileDestination)) {
attention là tu répètes 2 fois le move_uploaded_file, qui renvoi un bool.
retire la ligne 119. Le move_upload est exécuté dans le if !
sinon tu garde la 119, tu enregistres le résultat dans une variable et tu fais le if sur cette variable booléenne

2020-04-28 10:08 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +        return array ($dataTmp,$data);
utilises des crochets et renvoi  [$fileNameNew, $errors] (sans modif $data ici)

2020-04-28 10:08 UTC, sblondeau commented on src/Model/AdminRoomManager.php
>      public function selectRoomByAddress(): array
mettre tout ça dans le RoomManager

2020-04-28 10:08 UTC, sblondeau commented on src/Model/AdminRoomManager.php
> +    public static function bound($adminPrice, $statement)
je vois pas l'intéret de cette méthode, et encore moins pourquoi elle devrait etre statique ?
elle doit etre private et non statique
mais je pense que tu peux t'en passer ?!

2020-04-28 10:11 UTC, JuGault commented on src/Controller/AdminRoomController.php
> +                $dataTmp = $this->controlData($data, $dataTmp);
ce dataTmp correspond à mon tableau errors qui à la derniere fonction va contenir un tableau errors et un tableau avec tous les data+le nom du fichier upload. seul solution que j'ai trouvé

2020-04-28 10:14 UTC, JuGault commented on src/Model/AdminRoomManager.php
> +    public static function bound($adminPrice, $statement)
non car je l'utilise dans  le edit et php tic en me disant que je duplique trop le code

2020-04-28 10:27 UTC, JuGault commented on src/Controller/AdminRoomController.php
> +            if (!empty($_POST)) {
y'a un souci car j'atteint la page en post donc la method post est ok mais empty donc j'ai des erreurs

2020-04-28 10:31 UTC, JuGault commented on src/Controller/AdminRoomController.php
> +                $dataTmp = $this->controlDataFilter($data, $dataTmp);
si je les fusionne j'ai erreur cyclomatic

2020-04-28 18:59 UTC, Heldeenn submitted a review, later dismissed

2020-04-29 07:54 UTC, Heldeenn submitted a review, later dismissed

2020-05-01 18:40 UTC, sblondeau requested changes
les images uploadées ne doivent pas etre versionnées.
là tu les as visiblement versionnées avant d'ajouter dans le git ignore
il faut que tu les enlèves avec un git rm --cached -r assets/uploads/images

2020-05-01 18:40 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            list($fileNameNew, $errorsUpload) = [$fileNameNew,$errorsUpload];
cette ligne avec le list est absolument non nécessaire, elle fait exactement la meme chose que la ligne du dessus !!!

2020-05-01 18:40 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            unlink($fileNameNew);
je ne vois pas à quoi sert ce unlink ici !

2020-05-03 11:06 UTC, JuGault commented on src/Controller/AdminRoomController.php
> +            list($fileNameNew, $errorsUpload) = [$fileNameNew,$errorsUpload];
si je ne la met pas il me sort avoid variable undefined

2020-05-03 15:54 UTC, malyadev submitted a review, later dismissed
ok

2020-05-04 06:56 UTC, sblondeau requested changes

2020-05-04 06:56 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +        $adminRoomManager = new RoomManager();
$roomManager, si tu renommes la classe, la variable doit l'etre aussi

2020-05-04 06:56 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +        $fileNameNew = [];
fileNameNew est une string, donc si tu l'initialise, c'est avec une chaine vide, pas avec un tableau vide

2020-05-04 06:56 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +                list($fileNameNew,$errorsUpload) = [$fileNameNew,$errorsUpload];
la ligne avec le list() est à enlever

2020-05-04 06:56 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +                $errorsUpload['picture'] = "[{$file['picture']['name']}] l'extension '{$ext}' n'est pas autorisée,
pourquoi tu mets des crochets ici ?
$ext est le type myme, pas l'extension, ton nom de variable et ton message d'erreurs ne sont pas cohérents
Pourquoi pas un simple message d'erreur :
"Type de fichier incorrect. Les types de fichiers autorisés sont " . implode(', ', self::ALLOWED_EXT);

2020-05-04 06:56 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +                $errorsUpload['picture'] = "[{$file['picture']['name']}] erreur avec le code {$fileError}";
pourquoi reprendre [{$file['picture']['name']}]  devant chaque message d'erreur ?

2020-05-05 09:51 UTC, AnthonyMeyro submitted a review, later dismissed
k

2020-05-05 12:00 UTC, malyadev approved these changes
tutto bene

2020-05-05 15:07 UTC, sblondeau approved these changes

2020-05-05 15:07 UTC, merged