S03 US18 formulaire et sécurisation pour création animations
WildCodeSchool/orleans-php-2003-project-fjt pull request #67
Opened 2020-04-27 18:44 UTC by Heldeenn

2020-04-27 18:46 UTC, AnthonyMeyro submitted a review, later dismissed
Approved

2020-04-28 10:25 UTC, sblondeau requested changes
je te laisse travailler cette PR avec Julien car vous etre sur la meme problématique.

2020-04-28 10:25 UTC, sblondeau commented on src/Controller/AdminAnimationController.php
> +                if (in_array($fileExt, self::ALLOWED_EXT)) {
non ce n'est pas l'extension qu'il faut vérifier, mais le type MIME (donc revoir la constante et revoir la quete upload pour la récupération du type mime d'un fichier ;-))

2020-04-28 10:25 UTC, sblondeau commented on src/Controller/AdminAnimationController.php
> +                    if ($fileError === 0) {
revoir tes if qui sont tous imbriqués les uns dans les autres. Il faut mieux gérer un tableau $uploadErrors, ce n'est pas bien d'imbriquer les if (un, voire deux niveau d'imbrication max, là tu montes à 6)

2020-04-28 10:25 UTC, sblondeau commented on src/Controller/AdminAnimationController.php
> +                        $errors['image'] = "{$file['image']['name']} errored with code {$fileError}";
si tu utilisais des simples quote et de la concatenation, je trouve que ça serait plus lisible

2020-04-28 10:25 UTC, sblondeau commented on src/Controller/AdminAnimationController.php
> +                Merci de choisir un fichier JPG, JPEG, PNG ou GIF";
pour lister les type mime autorisé, plutot que de les mettre en dur dnas le message d'erreur, fais un implode(self::AUTORIZED_MIME) (qui va remplacer AUTORIZED_EXT)
ainsi si tu ajoutes ou retires type mime, le message d'erreur est automatiquement modifié et reste tjs cohérent

2020-04-28 10:25 UTC, sblondeau commented on src/Controller/AdminAnimationController.php
> +                            $fileDestination = '../public/assets/images/' . $fileNameNew;
le dossier dans lequel tu dois upload est /public/uploads par ex
mais ce n'est pas dans assets. Les image dans assets sont uniquement décoratives, statiques, non administrable). La tes images uploadées sont des données. Le chemin vers le dossier d'upload peut etre mis en constante pour etre facilement modifiable. Et penser à l'ajouter dans le gitignore car ces images ne doivent pas etre sur github

2020-04-28 19:40 UTC, AnthonyMeyro submitted a review, later dismissed
Toutbon!

2020-04-29 07:12 UTC, sblondeau requested changes

2020-04-29 07:12 UTC, sblondeau commented on src/Controller/AdminAnimationController.php
> +                } elseif (!in_array($file['image']['type'], self::ALLOWED_MIME)) {
non il ne faut pas utilisé ['type'] pour le MIME ce n'est pas suffisamment sécurisé.
utilise http://php.net/manual/en/function.mime-content-type.php comme décrit dans la quete ;-)

2020-05-04 15:52 UTC, AnthonyMeyro approved these changes
Approved

2020-05-05 07:27 UTC, sblondeau approved these changes

2020-05-05 07:27 UTC, merged