S03_US_09 sécurisation du formulaire de contact
WildCodeSchool/orleans-php-2003-project-fjt pull request #68
Opened 2020-04-27 20:05 UTC by malyadev

2020-04-27 21:54 UTC, JuGault requested changes

2020-04-27 21:54 UTC, JuGault commented on src/Controller/HomeController.php
> +
pourquoi créer 3 tableaux errors alors qu'un seul serait suffisant ?

2020-04-27 21:54 UTC, JuGault commented on public/assets/css/form.css
> +
a mon avis tu peut tous faire avec bootsrap ou presque.

2020-04-27 21:54 UTC, JuGault commented on src/View/contact/_form.html.twig
> +                    {% endif %}
je pense que si tu englobe label+input+message errors dans une div tu peut faire un truc plus propre et plus facilement exploitable en bootstrap

2020-04-27 21:54 UTC, JuGault commented on src/Controller/ContactController.php
>  }
ce controller doit etre supprimée?

2020-04-28 05:15 UTC, malyadev commented on src/Controller/HomeController.php
> +
parce que ça l'est pas :) cyclomatique complexity trop grande, obligé de découper

2020-04-28 05:15 UTC, malyadev commented on public/assets/css/form.css
> +
c'est ça le "presque" :p mais je vais revérifier

2020-04-28 05:22 UTC, malyadev commented on src/View/contact/_form.html.twig
> +                    {% endif %}
Bah... c'est le cas mdr la div form-group englobe le label l'input et le message d'erreur. Comme tous les autres champs d'ailleurs, la configuration est là même

2020-04-28 15:27 UTC, JuGault submitted a review, later dismissed

2020-04-28 15:55 UTC, sblondeau requested changes

2020-04-28 15:55 UTC, sblondeau commented on src/Controller/HomeController.php
> +        $maxNameLenght = 55;
length pas lenght

2020-04-28 15:55 UTC, sblondeau commented on src/Controller/HomeController.php
> +        } elseif (!preg_match('#[^0-9]#', $data['lastname'])) {
non ne fait pas ce type de verification, trop restrictif
et là ton expression régulière ne t'empeche pas de t'appeler "#{!@]/*" 
pour moi c'est pas génant au niveau de ton appli si qq'un veut mettre des nombres on des symboles, c'est pas vraiment bloquant et ça ne peut pas provoque d'erreurs ou de faille de sécurité, mets donc juste les verifs absolument nécessaires

2020-04-28 15:55 UTC, sblondeau commented on src/Controller/HomeController.php
> +            if (!preg_match('/^0\d(?:[ .-]?\d{2}){4}$/', $data['phone'])) {
idem, c'est trop compliqué à validé un phone
0601123456
06-01-02-03-04
06 06 06 06 06 
06.06.06.06.06
+33 06 06 06 06 06 etc...
sans compté les num étranger avec plus ou moins de chiffres... :D

2020-04-28 15:55 UTC, sblondeau commented on src/Controller/HomeController.php
> +        $maxMessageLenght = 300;
length

2020-04-28 15:55 UTC, sblondeau commented on src/Controller/HomeController.php
> +            $errors['message'] = 'La taille de votre message ne peut pas dépasser '.$maxMessageLenght.' lettres.';
cette limite à 300 est t-elle vraiment nécessaire ? si en bdd tu as bien un champ de type TEXT, il permet de mettre des dizaines de millier de caract, donc c'est pas justifié pour moi la limite à 300, on est pas sur Twitter :p

2020-04-28 16:22 UTC, malyadev commented on src/Controller/HomeController.php
> +        } elseif (!preg_match('#[^0-9]#', $data['lastname'])) {
C'est pas absolument nécessaire de vérifier si la personne mets bien un nom "valide" ? :o

2020-04-28 16:24 UTC, malyadev commented on src/Controller/HomeController.php
> +            $errors['message'] = 'La taille de votre message ne peut pas dépasser '.$maxMessageLenght.' lettres.';
J'ai jugé que oui mdr le champ message sert à décrire sa situation et éventuellement demander à être contacté, pas y mettre l'intégrale du Seigneur des Anneaux :(

2020-04-29 06:35 UTC, JuGault commented on src/Controller/HomeController.php
> +            $errors['message'] = 'La taille de votre message ne peut pas dépasser '.$maxMessageLenght.' lettres.';
300 c'peut au final quan tu fait un test

2020-05-04 14:49 UTC, sblondeau requested changes

2020-05-04 14:49 UTC, sblondeau commented on src/Controller/HomeController.php
> +                $data = [
pourquoi charger $_POST dans $data alors que tu as déjà fais ça ligne 30 via le array_map ? c'est à retirer

2020-05-04 14:49 UTC, sblondeau commented on src/Controller/HomeController.php
> +                $data = [
de plus tu voulais enregistrer en BDD non ? donc il faut que tu fasses le insert sinon ta US n'est pas fonctionnelle

2020-05-04 16:33 UTC, malyadev commented on src/Controller/HomeController.php
> +                $data = [
l'insert en bdd c'est une autre tâche du coup...

2020-05-06 16:00 UTC, closed without merging