S04 US37 création de la partie ajout d'adresse
WildCodeSchool/orleans-php-2003-project-fjt pull request #83
Opened 2020-05-03 17:05 UTC by JuGault

2020-05-04 08:15 UTC, malyadev requested changes

2020-05-04 08:15 UTC, malyadev commented on src/Controller/AdminRoomController.php
> +            $errors['name'] = 'Le nom de l\'adresse ne doit pas être vide';
juste l'adresse, pas le nom de l'adresse

2020-05-04 08:15 UTC, malyadev commented on src/Controller/AdminRoomController.php
> +            $errors['name'] = 'Le nom du logement est trop long';
je pense pas qu'il faille controler la longueur du nom du logement du coup :/

2020-05-04 08:15 UTC, malyadev commented on src/Controller/AdminRoomController.php
> +            $errors['name'] = 'Le nom de l\'adresse ne doit pas être vide';
ou bien est-ce le nom du logement ?

2020-05-04 08:26 UTC, malyadev submitted a review, later dismissed
je préfère :p

2020-05-04 10:12 UTC, sblondeau submitted a review, later dismissed

2020-05-04 10:12 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +            $errors['name'] = 'Le nom du logement est trop long';
mais si ! il faut ! car sinon pb en bdd si c'est trop long

2020-05-04 15:45 UTC, Heldeenn submitted a review, later dismissed

2020-05-05 07:31 UTC, sblondeau requested changes

2020-05-05 07:31 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +        return $this->twig->render('AdminRoom/addAddress.html.twig', ['post'=> $_POST ?? [], 'errors'=> $errors ?? []]);
ce n'est pas $_POST, mais  $data que tu dois envoyer à ta vue
donc plutot un 'data'=>$data ?? []

2020-05-05 07:31 UTC, sblondeau commented on src/Controller/AdminRoomController.php
> +        if ($_SERVER['REQUEST_METHOD'] === 'POST' && !empty($_POST)) {
en !empty($_POST) tjs inutile à mon sens

2020-05-05 13:21 UTC, AnthonyMeyro submitted a review, later dismissed
approved

2020-05-05 15:08 UTC, sblondeau submitted a review, later dismissed

2020-05-05 15:54 UTC, merged