S04 US23 création du formulaire de pré-admission
WildCodeSchool/orleans-php-2003-project-fjt pull request #86
Opened 2020-05-03 18:52 UTC by JuGault

2020-05-04 08:08 UTC, malyadev commented on public/assets/css/price.css
> +    list-style: none;
ça concerne pas la US le Hobbit master va pas aimer.....

2020-05-04 08:09 UTC, malyadev commented on src/View/Price/index.html.twig
> +</div>
aucun champs requis en html c'est fait exprès ou tu as oublié ?

2020-05-04 08:10 UTC, malyadev requested changes
regarde

2020-05-04 08:11 UTC, JuGault commented on public/assets/css/price.css
> +    list-style: none;
si c'la liste des document dans le formulaire

2020-05-04 08:11 UTC, JuGault commented on src/View/Price/index.html.twig
> +</div>
prochaine US

2020-05-04 10:17 UTC, sblondeau requested changes

2020-05-04 10:17 UTC, sblondeau commented on src/View/Price/index.html.twig
> +                    <input class="my-3 btn btn-primary btn-lg" type="reset" value="Annuler">
pas la peine de mettre un bouton reset (c'est plus trop "à la mode" ;-) et ça sert pas à grand chose coté UX)

2020-05-04 10:17 UTC, sblondeau commented on src/View/Price/index.html.twig
> +</div>
je suis d'accord avec Yannice, là tu as plutot fait une tache de US, et pas une US
la US c'est en tant que visiteur, je peux envoyer mon dossier
pas "en tant que visiteur, j'ai accès à un formualire non fonctionnel" ;-) 
donc j'ajouterais le traitement ici.

2020-05-06 12:00 UTC, malyadev approved these changes
ça fait beaucoup de Travis là quand-même

2020-05-06 16:16 UTC, sblondeau approved these changes

2020-05-06 16:23 UTC, merged