S04 US19 admin : modification animation
WildCodeSchool/orleans-php-2003-project-fjt pull request #95
Opened 2020-05-05 12:32 UTC by Heldeenn

2020-05-05 13:19 UTC, AnthonyMeyro submitted a review, later dismissed
approved

2020-05-05 15:53 UTC, sblondeau requested changes

2020-05-05 15:53 UTC, sblondeau commented on src/Controller/AdminAnimationController.php
> +            $fileExt = pathinfo($file['image']['name'], PATHINFO_EXTENSION);
fileExtension

2020-05-05 15:53 UTC, sblondeau commented on src/Controller/AdminAnimationController.php
> +            if (!empty($_FILES['image']['name'])) {
je testerais plutot ici le code erreur à 0 ou non, si c'est 0 tu continue. ça me semble plus cohérent que de tester l'existence ou non du name

2020-05-05 15:53 UTC, sblondeau commented on src/Controller/AdminAnimationController.php
> +                    $errors['image'] = $file['image']['name'] . ' L\'extension ' . $fileExt . ' n\'est pas autorisée.
Le type mime $mimeType n'est pas autorisé...

2020-05-06 09:13 UTC, malyadev approved these changes
Oui

2020-05-06 09:55 UTC, sblondeau approved these changes

2020-05-06 09:55 UTC, merged