bgNavbarFixed on other pages and contact linked correctly
WildCodeSchool/orleans-php-2003-project-fjt pull request #98
Opened 2020-05-05 18:39 UTC by AnthonyBerduck

2020-05-05 19:13 UTC, Heldeenn submitted a review, later dismissed

2020-05-06 06:50 UTC, sblondeau requested changes

2020-05-06 06:50 UTC, sblondeau commented on public/assets/css/navbarHome.css
> +    background-color: rgba(0,0,0,0);
variable css

2020-05-06 06:50 UTC, sblondeau commented on public/assets/css/navbarHome.css
> +    background-color: rgba(0,0,0,0);
et sinon, il existe la couleur "transparent" également ;-)

2020-05-06 07:10 UTC, Heldeenn approved these changes

2020-05-06 07:17 UTC, sblondeau approved these changes

2020-05-06 07:17 UTC, merged